version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
    volumes:
      - ./:/usr/src/app
    networks:
      - app_network

volumes:
  # Nếu app cần volume riêng, thêm ở đây

networks:
  app_network:
    driver: bridge
