version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx_multi_tenant_local
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
