version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio1
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: vienspkT1!
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - minio_network

volumes:
  minio_data:

networks:
  minio_network:
    driver: bridge
